apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: "recommendation-code-assignment"
  annotations:
    github.com/project-slug: "scentmate/recommendation-code-assignment"
spec:
  type: interview
  lifecycle: production
